name: ci

on: pull_request

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6"
      - run: go build
      - run: |
          ./install asdf
          ./install bashrc
          source ~/.bashrc
          ./install all

